name: Test

on:
  pull_request:
    branches:
    - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Pseudo release
        run: buildtools/release.sh
